name: las
description: A new Flutter package project.
version: 0.0.1-snapshot
homepage: https://github.com/andreclinio/las


environment:
  sdk: ">=2.16.1 <3.0.0"
 

dependencies:

dev_dependencies:
  test: ^1.16.8
  pedantic: ^1.11.0

